name: Deploy preprod on push feature

on:
  push:
    branches:
    - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1 ]

    steps:
      - name: checkout preprod-myminicom
        uses: actions/checkout@v3

      - name: Restore the Composer cache directory
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-'8.0'-composer-

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --prefer-dist --no-interaction

      - name: Zip artifact for deployment
        run: zip -r release.zip website/app/* website/vendor/* website/wordpress-core/* -x ".git/*" -x ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
  #    - name: create or replace backup release
  #      uses: appleboy/ssh-action@v0.1.10
  #     with:
  #        host: ${{ secrets.DEPLOY_HOST }}
  #        username: ${{ secrets.DEPLOY_USER }}
  #        key: ${{ secrets.DEPLOY_KEY }}
  #        port: 22
  #        script: "[ ! -d ~/preprod-myminicom/website ] || rm -rf ~/preprod-myminicom/old_website ~/preprod-myminicom/website/vendor ~/preprod-myminicom/website/wordpress-core && mv -fu ~/preprod-myminicom/website ~/preprod-myminicom/old_website"

      - name: checkout preprod-myminicom
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: unzip artifact for deployment
        run: |
         unzip -o release.zip

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./website
          remote_path: ~/preprod-myminicom
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: create new Symlink
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            ln -nsrf ~/preprod-myminicom/shared/.env ~/preprod-myminicom/website/.env
            ln -nsrf ~/preprod-myminicom/shared/uploads ~/preprod-myminicom/website/app/uploads
            ln -nsrf ~/preprod-myminicom/shared/cache ~/preprod-myminicom/website/app/cache
            ln -nsrf ~/preprod-myminicom/shared/w3tc-config ~/preprod-myminicom/website/app/w3tc-config
            rm ~/preprod-myminicom/website/.htaccess
            ln -nsrf ~/preprod-myminicom/shared/.htaccess ~/preprod-myminicom/website/.htaccess
            ln -nsrf ~/preprod-myminicom/shared/.htpasswd ~/preprod-myminicom/website/.htpasswd